# cURL commands related to Bar docker container
# written with REST HTTP

@hostname = localhost
@port = 4000

### GET /v1/meta
curl -X GET http://{{hostname}}:{{port}}/v1/meta

### GET /v1/info
curl -X GET http://{{hostname}}:{{port}}/v1/info
