# -------------------
# docker-compose to build and run both Foo and Bar server at once
# -------------------

version: '3'
services:

  # defining the Foo server and the build context
  foo-service:
    build:
      dockerfile: Dockerfile
      context: ./foo-server
    # port mapping configurations
    ports:
      - 3000:3000
    # environment variables
    environment:
      - FOO_SERVER_ENV_MESSAGE="A custom message set using the environment variable"

  # defining the Bar server and the build context
  bar-service:
    build:
      dockerfile: Dockerfile
      context: ./bar-server
    # port mapping configurations
    ports:
      - 4000:4000
    environment:
      - BAR_SERVER_ENV_MESSAGE="Another custom message set using the environment variable"
