# -------------------
# Dockerfile for the nginx server
# -------------------

# create an image using the nginx as the base image
FROM nginx

# copy the default.conf from the local directory and place it inside the
# container
COPY ./default.con /etc/nginx/conf.d/default.conf
