# -------------------
# docker-compose to build and run Bar server with volume mount
# -------------------

version: '3'
services:

  # defining the Bar server and the build context
  bar-service:
    build: 
      dockerfile: Dockerfile
      context: ./bar-server
    # port mapping configurations
    ports:
      - 4000:4000
    # environment variables
    environment: 
      - BAR_SERVER_ENV_MESSAGE="Another custom message set using the environment variable"
    # volume mount
    volumes: 
      # bookmark mount configuration to not to touch and change the node_modules directory inside the container
      - /usr/app/node_modules
      # mount configuration to map the bar-server directory to the /usr/app directory
      - ./bar-server:/usr/app
