# -------------------
# yaml configuration to create a pod for the Foo server
# -------------------

apiVersion: v1
# kind is configured as Pod
kind: Pod

metadata:
  name: foo-service
  labels:
    name: foo-service

spec:
  # container configurations. the image is pulled from the DockerHub
  containers:
  - name: foo-service
    image: athiththan11/foo-server:1.0.0

    # resource configurations for containers
    resources:
      limits:
        memory: "128Mi"
        cpu: "125m"
    
    # port configurations
    # even-though port configurations are done, the Foo server will not be 
    # accessible from your local machine. Follow the `11--k8s-pod-foo-server-nodeport`
    # to access the Foo server with the NodePort configurations
    ports:
      - containerPort: 3000
